# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b69710a7592aab80b0f7942149fefcbb84715f071f216471a5be9fa1fcbc18f7855f7b33cbd0da7b7f6b24a3bf7259f49297ed9467131a30e9614a59a513c50b

test:
  secret_key_base: 46f339933e646d0f5f2f6eb1a77c9e38b10de0216122a3677dd4b5fab965b51960af411385ba633f2eb9ca40871b582b5055160a88af5e777a061ecb351ce3cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
